version: "3"

networks:
  app-tier:
    driver: bridge

services:
  memgraph-mage:
    build: ./memgraph
    ports:
      - "7687:7687"
    entrypoint:
      [
        "/usr/lib/memgraph/memgraph",
        "--telemetry-enabled=false",
        "--kafka-bootstrap-servers=kafka:9092",
        "--query-modules-directory=/transformations",
        "--log-level=TRACE",
      ]
    networks:
      - app-tier

  zookeeper:
    image: "bitnami/zookeeper:3.7"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
    logging:
      driver: none

  kafka:
    image: "bitnami/kafka:2"
    logging:
      driver: none
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - app-tier

  core:
    image: tianon/true
    restart: "no"
    depends_on:
      - kafka
      - memgraph

  stream:
    build:
      context: ./
      dockerfile: ./stream/Dockerfile
    entrypoint: ["python3", "produce.py", "--stream-delay", "2.0"]
    environment:
      KAFKA_IP: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: "retweets"
    networks:
      - app-tier
